Repository appwrite/website, pull requests merged in 2023-11, with the labels that each got.

#316 update privacy policy
  src/routes/privacy/+page.svelte
Labels: documentation

#323 Fix FOUC
  src/app.html
  src/hooks/server.ts
  src/lib/constants.ts
  src/lib/layouts/Main.svelte
  src/routes/api/blog/+server.ts
  src/routes/docs/references/+layout.svelte
  src/routes/docs/references/[version]/[platform]/[service]/+layout.svelte
  src/scss/7-components/_main-header.scss
  src/scss/7-components/_top-banner.scss
Labels: bug

#303 Doc: Removed alt attributes in cards
  src/routes/docs/+page.svelte
  src/routes/docs/CodeCard.svelte
  src/routes/docs/tutorials/+page.svelte
Labels: hacktoberfest-accepted, a11y

#273 Adjust Docs Hero & Tech section
  src/lib/components/Spline.svelte
  src/routes/docs/+page.svelte
  src/scss/abstract/mixins/_border-gradient.scss
  static/images/bgs/docs-blur-1.svg
Labels: ui/ux

#287 Refactor tutorials page structure & design
  src/icons/optimized/vue.svg
  src/icons/output/aw-icon.eot
  src/icons/output/aw-icon.svg
  src/icons/output/aw-icon.symbol.svg
  src/icons/output/aw-icon.ttf
  src/icons/output/aw-icon.woff
  src/icons/output/aw-icon.woff2
  src/icons/svg/vue.svg
  src/markdoc/layouts/Tutorial.svelte
  src/markdoc/nodes/Link.svelte
  src/routes/docs/quick-starts/sveltekit/+page.markdoc
  src/routes/docs/tutorials/+page.svelte
  src/routes/docs/tutorials/+page.ts
  src/routes/docs/tutorials/android/step-1/+page.markdoc
  src/routes/docs/tutorials/apple/step-1/+page.markdoc
  src/routes/docs/tutorials/flutter/step-1/+page.markdoc
  src/routes/docs/tutorials/react/step-1/+page.markdoc
  src/routes/docs/tutorials/sveltekit-auth/step-1/+page.markdoc
  src/routes/docs/tutorials/sveltekit/step-1/+page.markdoc
  src/routes/docs/tutorials/sveltekit/step-2/+page.markdoc
  src/routes/docs/tutorials/sveltekit/step-4/+page.markdoc
  src/routes/docs/tutorials/sveltekit/step-5/+page.markdoc
  src/routes/docs/tutorials/sveltekit/step-6/+page.markdoc
  src/routes/docs/tutorials/sveltekit/step-7/+page.markdoc
  src/routes/docs/tutorials/sveltekit/step-8/+page.markdoc
  src/routes/docs/tutorials/vue/step-1/+page.markdoc
  vite.config.ts
Labels: ui/ux

#243 #84 Nuxt tutorial
  src/routes/docs/tutorials/nuxt/+layout.svelte
  src/routes/docs/tutorials/nuxt/+layout.ts
  src/routes/docs/tutorials/nuxt/+page.ts
  src/routes/docs/tutorials/nuxt/step-1/+page.markdoc
  src/routes/docs/tutorials/nuxt/step-2/+page.markdoc
  src/routes/docs/tutorials/nuxt/step-3/+page.markdoc
  src/routes/docs/tutorials/nuxt/step-4/+page.markdoc
  src/routes/docs/tutorials/nuxt/step-5/+page.markdoc
  src/routes/docs/tutorials/nuxt/step-6/+page.markdoc
  src/routes/docs/tutorials/nuxt/step-7/+page.markdoc
  src/routes/docs/tutorials/nuxt/step-8/+page.markdoc
Labels: documentation, hacktoberfest-accepted

#271 Add tutorial for android java
  src/routes/docs/tutorials/android/step-1/+page.markdoc
  src/routes/docs/tutorials/android/step-2/+page.markdoc
  src/routes/docs/tutorials/android/step-3/+page.markdoc
  src/routes/docs/tutorials/android/step-4/+page.markdoc
  src/routes/docs/tutorials/android/step-5/+page.markdoc
  src/routes/docs/tutorials/android/step-6/+page.markdoc
  src/routes/docs/tutorials/android/step-7/+page.markdoc
  src/routes/docs/tutorials/android/step-8/+page.markdoc
  static/images/docs/tutorials/dark/recipewrite-collection-attributes.png
  static/images/docs/tutorials/dark/recipewrite-collection-indexes.png
  static/images/docs/tutorials/dark/recipewrite-collection-permissions.png
  static/images/docs/tutorials/recipewrite-asset-studio.png
  static/images/docs/tutorials/recipewrite-collection-attributes.png
  static/images/docs/tutorials/recipewrite-collection-indexes.png
  static/images/docs/tutorials/recipewrite-collection-permissions.png
  static/images/docs/tutorials/recipewrite-empty-activity.png
  static/images/docs/tutorials/recipewrite-new-project.png
  static/images/docs/tutorials/recipewrite-user-flow.png
Labels: documentation, hacktoberfest-accepted

#275 Added Flutter Authentication Deepdive
  src/routes/docs/tutorials/flutter-auth/+layout.svelte
  src/routes/docs/tutorials/flutter-auth/+layout.ts
  src/routes/docs/tutorials/flutter-auth/+page.ts
  src/routes/docs/tutorials/flutter-auth/step-1/+page.markdoc
  src/routes/docs/tutorials/flutter-auth/step-2/+page.markdoc
  src/routes/docs/tutorials/flutter-auth/step-3/+page.markdoc
  src/routes/docs/tutorials/flutter-auth/step-4/+page.markdoc
  src/routes/docs/tutorials/flutter-auth/step-5/+page.markdoc
  src/routes/docs/tutorials/flutter-auth/step-6/+page.markdoc
  src/routes/docs/tutorials/flutter-auth/step-7/+page.markdoc
Labels: hacktoberfest-accepted

#301 doc: implemented Appwrite auth functionalities with Vuejs
  src/routes/docs/tutorials/vue-auth/+layout.svelte
  src/routes/docs/tutorials/vue-auth/+layout.ts
  src/routes/docs/tutorials/vue-auth/+page.ts
  src/routes/docs/tutorials/vue-auth/step-1/+page.markdoc
  src/routes/docs/tutorials/vue-auth/step-10/+page.markdoc
  src/routes/docs/tutorials/vue-auth/step-2/+page.markdoc
  src/routes/docs/tutorials/vue-auth/step-3/+page.markdoc
  src/routes/docs/tutorials/vue-auth/step-4/+page.markdoc
  src/routes/docs/tutorials/vue-auth/step-5/+page.markdoc
  src/routes/docs/tutorials/vue-auth/step-6/+page.markdoc
  src/routes/docs/tutorials/vue-auth/step-7/+page.markdoc
  src/routes/docs/tutorials/vue-auth/step-8/+page.markdoc
  src/routes/docs/tutorials/vue-auth/step-9/+page.markdoc
Labels: documentation, hacktoberfest-accepted

#381 fix process env
  vite.config.ts
Labels: bug

#344 Replace pixelated SVGs
  package.json
  pnpm-lock.yaml
  src/routes/+page.svelte
  src/routes/assets/+page.svelte
  src/routes/assets/bg.png
  src/routes/company/+page.svelte
  src/routes/company/bg-left.png
  src/routes/company/bg-right.png
  src/routes/contact-us/+page.svelte
  src/routes/contact-us/bg.png
  src/routes/docs/+page.svelte
  src/routes/docs/blur-1.png
  src/routes/docs/blur-2.png
  src/routes/heroes/+page.svelte
  src/routes/heroes/bg-pre.png
  src/routes/heroes/teal-blur.png
  src/routes/pricing/+page.svelte
  src/routes/pricing/bg.png
  src/routes/top-page-dark.png
  static/images/bgs/assets-bg.svg
  static/images/bgs/contact-us.png
  static/images/bgs/docs-blur-2.svg
  static/images/bgs/heroes-pre.png
  static/images/bgs/heroes-pre.svg
  static/images/bgs/pre-footer.svg
  static/images/bgs/pricing-hero.svg
  static/images/bgs/top-page-dark.svg
  static/images/bgs/top-page-light.png
  static/images/heroes/teal-blur.svg
  vite.config.ts
Labels: enhancement
