Repository appwrite/website, pull requests merged in 2023-12, with the labels that each got.

#350 doc: add Refine tutorial
  src/icons/optimized/refine.svg
  src/icons/output/_variables.scss
  src/icons/output/aw-icon.css
  src/icons/output/aw-icon.eot
  src/icons/output/aw-icon.scss
  src/icons/output/aw-icon.svg
  src/icons/output/aw-icon.symbol.svg
  src/icons/output/aw-icon.ttf
  src/icons/output/aw-icon.woff
  src/icons/output/aw-icon.woff2
  src/icons/output/info.json
  src/icons/svg/refine.svg
  src/lib/components/Technologies.svelte
  src/routes/docs/quick-starts/+page.svelte
  src/routes/docs/quick-starts/refine/+page.markdoc
  src/routes/docs/tutorials/+page.svelte
  src/routes/docs/tutorials/refine/+layout.svelte
  src/routes/docs/tutorials/refine/+layout.ts
  src/routes/docs/tutorials/refine/+page.ts
  src/routes/docs/tutorials/refine/step-1/+page.markdoc
  src/routes/docs/tutorials/refine/step-2/+page.markdoc
  src/routes/docs/tutorials/refine/step-3/+page.markdoc
  src/routes/docs/tutorials/refine/step-4/+page.markdoc
  src/routes/docs/tutorials/refine/step-5/+page.markdoc
  src/routes/docs/tutorials/refine/step-6/+page.markdoc
  src/routes/docs/tutorials/refine/step-7/+page.markdoc
  static/images/docs/tutorials/refine/posts-collection-dark.png
  static/images/docs/tutorials/refine/posts-collection-light.png
  static/images/docs/tutorials/refine/refine-admin-panel-dark.png
  static/images/docs/tutorials/refine/refine-admin-panel-light.png
  static/images/docs/tutorials/refine/refine-create-page.png
  static/images/docs/tutorials/refine/refine-edit-page.png
  static/images/docs/tutorials/refine/refine-list-page.png
  static/images/docs/tutorials/refine/refine-login-page.png
  static/images/docs/tutorials/refine/refine-show-page.png
  static/images/docs/tutorials/refine/refine-welcome-page.png
  static/images/platforms/dark/refine.svg
  static/images/platforms/light/refine.svg
  static/images/platforms/refine.svg
Labels: documentation

#418 Fix docs hero
  src/routes/docs/+page.svelte
Labels: bug

#348 fix: Update aria-labels for social icons in footer
  src/lib/components/MainFooter.svelte
  src/lib/constants.ts
  src/routes/community/+page.svelte
  src/routes/contact-us/+page.svelte
Labels: bug

#259 Changed z-index of mobile header to 120.
  src/scss/7-components/_main-header.scss
  src/scss/7-components/_mobile-header.scss
Labels: ui/ux
