Repository appwrite/website, pull requests merged in 2023-10, with the labels that each got.

#142 Resolve Issue #136
  src/routes/docs/tutorials/react/step-3/+page.markdoc
  src/routes/docs/tutorials/sveltekit/step-3/+page.markdoc
  src/routes/docs/tutorials/vue/step-3/+page.markdoc
Labels: hacktoberfest

#164 QA Fixes - First batch
  package.json
  pnpm-lock.yaml
  src/lib/animations/OpenSource.svelte
  src/lib/components/Article.svelte
  src/lib/components/Carousel.svelte
  src/lib/components/MainFooter.svelte
  src/lib/components/Spline.svelte
  src/lib/components/Tooltip.svelte
  src/lib/layouts/DocsTutorial.svelte
  src/lib/utils/references.ts
  src/markdoc/nodes/Fence.svelte
  src/routes/community/+page.svelte
  src/routes/community/EventCard.svelte
  src/routes/company/careers/+page.ts
  src/routes/docs/+page.svelte
  src/routes/docs/CodeCard.svelte
  src/scss/6-elements/_tooltip.scss
  src/scss/7-components/_code-snippet.scss
  src/scss/7-components/_references-menu.scss
  src/scss/8-sequences/_grid-articles.scss
  static/images/bgs/docs-blur-1.svg
  static/images/bgs/docs-blur-2.svg
Labels: bug

#186 Add article about new logo
  src/routes/blog/author/dennis-ivy/+page.markdoc
  src/routes/blog/author/haimantika-mitra/+page.markdoc
  src/routes/blog/author/jade-baudchon/+page.markdoc
  src/routes/blog/author/laura-du-ry/+page.markdoc
  src/routes/blog/post/the-journey-and-meaning-behind-our-new-logo/+page.markdoc
  src/scss/6-elements/_media-container.scss
  static/images/blog/the-journey-and-meaning-behind-our-new-logo/break.png
  static/images/blog/the-journey-and-meaning-behind-our-new-logo/cover.png
  static/images/blog/the-journey-and-meaning-behind-our-new-logo/drafts.png
  static/images/blog/the-journey-and-meaning-behind-our-new-logo/lines.png
  static/images/blog/the-journey-and-meaning-behind-our-new-logo/new_logo.png
  static/images/blog/the-journey-and-meaning-behind-our-new-logo/old_logo.png
Labels: enhancement

#221 Heroes page fixes
  src/lib/layouts/Docs.svelte
  src/lib/layouts/Main.svelte
  src/routes/heroes/+page.svelte
  src/routes/heroes/HeroCard.svelte
  src/scss/6-elements/_button.scss
  src/scss/6-elements/_container.scss
  src/scss/6-elements/_icon-button.scss
  src/scss/6-elements/_select.scss
  src/scss/7-components/_index.scss
  src/scss/7-components/_main-header.scss
  src/scss/7-components/_mobile-header.scss
  src/scss/7-components/_scroll-carousel.scss
  src/scss/9-grids/_grid-side-nav.scss
  static/images/bgs/heroes-pre.svg
  static/images/heroes/avatar-1.png
  static/images/heroes/avatar-2.png
  static/images/heroes/avatar-3.png
  static/images/heroes/bg.png
  static/images/heroes/photos/1.png
  static/images/heroes/photos/2.png
  static/images/heroes/photos/3.png
  static/images/heroes/photos/4.png
  static/images/heroes/photos/5.png
  static/images/heroes/teal-blur.svg
  static/images/temp/bg-side-heroes.png
Labels: bug

#263 Update the msg91 SMS provider docs
  src/routes/docs/advanced/self-hosting/sms/+page.markdoc
Labels: documentation

#262 Hotfix: Image z-index & scrollToTop
  src/app.html
  src/lib/actions/scrollToTop.ts
  src/lib/layouts/DocsArticle.svelte
  src/lib/layouts/DocsTutorial.svelte
  src/markdoc/nodes/Image.svelte
  src/routes/docs/references/[version]/[platform]/[service]/+page.svelte
  src/routes/kitchensink/+page.svelte
Labels: bug

#137 Add Thomas's svelte auth guide
  src/lib/utils/code.ts
  src/routes/docs/tutorials/sveltekit-auth/+layout.svelte
  src/routes/docs/tutorials/sveltekit-auth/+layout.ts
  src/routes/docs/tutorials/sveltekit-auth/+page.ts
  src/routes/docs/tutorials/sveltekit-auth/step-1/+page.markdoc
  src/routes/docs/tutorials/sveltekit-auth/step-2/+page.markdoc
  src/routes/docs/tutorials/sveltekit-auth/step-3/+page.markdoc
  src/routes/docs/tutorials/sveltekit-auth/step-4/+page.markdoc
  src/routes/docs/tutorials/sveltekit-auth/step-5/+page.markdoc
  src/routes/docs/tutorials/sveltekit-auth/step-6/+page.markdoc
  src/routes/docs/tutorials/sveltekit-auth/step-7/+page.markdoc
  src/scss/hljs.css
Labels: documentation

#237 docs: Fix import path typo in Nextjs Quickstart documentation
  src/routes/docs/quick-starts/nextjs/+page.markdoc
Labels: documentation

#288 Disable Spline Embeds
  src/lib/components/Spline.svelte
  src/routes/+page.svelte
Labels: bug

#207 Added new blog
  src/routes/blog/post/behind-the-pr-tales-from-the-open-source-world/+page.markdoc
  static/images/blog/Behind_the_pull_request_Stories_from_contributors.png
Labels: documentation

#196 feat(docs): add pagination tutorial and related files
  src/routes/docs/tutorials/pagination/+layout.svelte
  src/routes/docs/tutorials/pagination/+layout.ts
  src/routes/docs/tutorials/pagination/+page.ts
  src/routes/docs/tutorials/pagination/step-1/+page.markdoc
  src/routes/docs/tutorials/pagination/step-10/+page.markdoc
  src/routes/docs/tutorials/pagination/step-2/+page.markdoc
  src/routes/docs/tutorials/pagination/step-3/+page.markdoc
  src/routes/docs/tutorials/pagination/step-4/+page.markdoc
  src/routes/docs/tutorials/pagination/step-5/+page.markdoc
  src/routes/docs/tutorials/pagination/step-6/+page.markdoc
  src/routes/docs/tutorials/pagination/step-7/+page.markdoc
  src/routes/docs/tutorials/pagination/step-8/+page.markdoc
  src/routes/docs/tutorials/pagination/step-9/+page.markdoc
Labels: documentation, hacktoberfest-accepted

#179 📚 Documentation: Tutorial for Next JS
  src/routes/docs/tutorials/nextjs/+layout.svelte
  src/routes/docs/tutorials/nextjs/+layout.ts
  src/routes/docs/tutorials/nextjs/+page.ts
  src/routes/docs/tutorials/nextjs/step-1/+page.markdoc
  src/routes/docs/tutorials/nextjs/step-2/+page.markdoc
  src/routes/docs/tutorials/nextjs/step-3/+page.markdoc
  src/routes/docs/tutorials/nextjs/step-4/+page.markdoc
  src/routes/docs/tutorials/nextjs/step-5/+page.markdoc
  src/routes/docs/tutorials/nextjs/step-6/+page.markdoc
  src/routes/docs/tutorials/nextjs/step-7/+page.markdoc
  src/routes/docs/tutorials/nextjs/step-8/+page.markdoc
  src/routes/docs/tutorials/nextjs/step-9/+page.markdoc
  static/images/docs/tutorials/collection-permissions.png
  static/images/docs/tutorials/dark/collection-permissions.png
  static/images/docs/tutorials/dark/expense-tracker-collection.png
  static/images/docs/tutorials/expense-tracker-app.png
  static/images/docs/tutorials/expense-tracker-collection.png
Labels: documentation, hacktoberfest-accepted

#302 (fix):Update Heading Tags in Side Navbar for Improved Accessibility
  src/lib/layouts/Sidebar.svelte
Labels: hacktoberfest-accepted, a11y
